# Generated by Django 5.0.5 on 2024-05-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_svgimage_rectangle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
