# Generated by Django 5.0.5 on 2024-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
